> `??` 의미 : 추가로 알아봐야함

## Intro
- 함수 내 오류 발생 : 예외 던짐 (throw)
- 함수 호출하는 쪽 : 처리 (catch) > 미처리시 함수 호출 스택을 거슬러 올라가 처리될때까지 rethrow
- throw 또한 식

## 1. try, catch, finally

* java 코드 예시 : 함수가 던질 수 있는 모든 예외 명시
```java
void method() throws Exception1,Exception2, ... ExceptionN {
   // 메서드의 내용
}
```

* kotlin 코드 예시
```kotlin
import java.io.BufferedReader
import java.io.StringReader

fun readNumber(reader: BufferedReader): Int?{ // <- 반환 타입에 throws절 없음
    try{
        val line = reader.readLine()
        return Integer.parseInt(line)
    }
    catch(e: NumberFormatException){
        println("예외발생 $e")
        return null
    }
    finally{
        reader.close()
    }
}

fun main(){
    val reader = BufferedReader(StringReader("숫자가 아닌 값"))
    println(readNumber(reader))
}
```

* 실행 결과

```bash
예외발생 java.lang.NumberFormatException: For input string: "숫자가 아닌 값"
null
```

### checked exception vs unchecked exception
- checked exception : 컴파일 단계에서 체크하기 때문에 붙여짐
  -  개발자는 예외를 잡아 처리하거나 던져야함
- unchecked exception(RuntimeException)
  - 개발자가 예외처리하지 않아도 
![image](https://github.com/user-attachments/assets/c512f307-1d2c-461f-8a9c-40948ac0e9fe)


- 개발자들이 예외를 잡되 처리하지 않거나 무시하는 경우가 흔함
- 최신 JVM 언어와 마찬가지로 kotlin은 구별하지 않음 -> ??
- 함수가 던지는 예외를 지정하거나 잡아내지도 않음 -> ??




## 2. try를 식으로 사용
* (참고) 윗 코드에서 수정됨
  
```kotlin
import java.io.BufferedReader
import java.io.StringReader

fun readNumber(reader: BufferedReader): kotlin.Int?{
    val number = try{
        // try의 값을 변수에 대입 가능
        // try의 본문을 반드시 중괄호로 둘러싸야함
        // 마지막 식의 값이 전체 결과 값
        Integer.parseInt(reader.readLine()) 
    }
    catch(e: NumberFormatException){
        // 예외가 발생한 경우 catch 블록 다음의 코드는 실행되지 않음
        // 하지만, 계속 진행하고 싶다면, catch 블록도 값을 만들면 됨
        // 마지막 식의 값이 전체 결과 값
        null 
    }
    
    reader.close()
    
    return number
}

fun main(){
    val reader = BufferedReader(StringReader("1234"))
    println(readNumber(reader))
}
```

### 더 공부하고 싶다면?
- 6.2.6 : throw식 활용법
- 8.2.8 : 자바7의 자원을 사용하는 try-with-resource > 코틀린은 문법을 지원하지 않고 라이브러리 함수로 구현됨
